### ISSUE TITLE
Scheduled payments are not decoded because of a typo

### ISSUE THREAD

**Issue by mbernson** [bunq/sdk_php#70] opened 2017-11-13 11:26 UTC
There is a typo in the `bunq\Model\Generated\Endpoint\SchedulePayment` class. It has the constant `const OBJECT_TYPE = 'SchedulePayment';` while the API returns an object of type `ScheduledPayment`. When I change the constant to this, it works fine.

## Steps to reproduce:
1. Run this piece of code: https://gist.github.com/mbernson/dd8c966e277b4acd820463335cd47e24

## What should happen:
1. I see a var_dump of my scheduled payments.

## What happens:
1. `PHP Notice:  Undefined index: SchedulePayment in /Users/mathijs/Code/bunqapibouwsel/vendor/bunq/sdk_php/src/Model/Core/BunqModel.php on line 115`

## Extra info:
- Tested on bunq/sdk_php version 0.12.2 and the production bunq API

**Comment by OGKevin** [comment] 2017-11-13 12:18
Hey Mathijs,

Thanks for this report, will try and reproduce shortly and see whats going on here. Unfortunately because this file is in the generated folder this requires a change on bunq’s side and therefore is not a quick fix. This means that it won’t be fixed in the release of this week.

**Comment by OGKevin** [comment] 2017-11-13 12:55
Well, it can of course be hotfixed as well because it’s a 🐜 .

**Closed** 2017-11-15 08:56 UTC
Labels: bug, cause found, needs core regeneration, reproduced

**Comment by OGKevin** [comment] 2017-11-15 14:03
FYI @mbernson
